### PR TITLE
Allow any error type in handler result

### PR DESCRIPTION
**Pull request by djc**
r? @valkum

### CODE REVIEW

**Comment by valkum** [comment]
See my PR against this branch for tests and usage. This is a good step, but I think we should do more to improve ergonomics.

**Comment by djc** [comment]
See the second commit. That would get us in trouble with Epoxide, though, which has this impl:

```rust
impl FromContext<'_, App> for Session {
    fn from_context(
        app: &'_ Arc<App>,
        req: &'_ Parts,
        _: &mut mendes::application::PathState,
        _: &mut Option<<App as Application>::RequestBody>,
    ) -> Result<Session, Error> {
        app.cookie::<Self>(&req.headers)
            .ok_or_else(|| Error::forbidden("not logged in"))
    }
}
```

I guess we could add a `mendes::Error` variant for `Cookie(cookies::Error)`?

**Comment by valkum** [comment]
> 
> All other things being equal, this feels preferable to me?

I agree. Do you want me to update the PR test adds the tests so that PR can be merged into this PR or do you want to merge this first and merge the test PR into main afterwards?

**Comment by djc** [comment]
> I agree. Do you want me to update the PR test adds the tests so that PR can be merged into this PR or do you want to merge this first and merge the test PR into main afterwards?

I don't really care -- the state on `main` will be the same either way after both get merged, right? If you agree that this PR does the right thing per your tests, then let's merge this and merge your PR right after.

**Comment by djc** [comment]
Alright, that makes sense to me. I'll see what happens if I plug this into bolt before we merge it.

**Comment by djc** [comment]
Seems to just work in bolt. Merging!

**Pull request merged**
